name: Build NixOS Iso

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    # manual trigger
  #schedule:
  #  - cron: '0 0 * * *' # https://crontab.guru

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05

      - run: sudo apt update

      - run: sudo apt search qemu

      - run: sudo apt install qemu-user-aarch64

      - run: nix-build

      - name: list files
        run: |
          ls -l

      - name: Release package
        uses: softprops/action-gh-release@master
        with:
          name: nixos
          tag_name:  nixos
          body: |
            nixos
          files: |
            out/*
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
