name: Build NixOS Iso

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0,7,14 * * *' # https://crontab.guru  # build every 7 hours, GH times out at 6 H 

permissions:
  contents: write

jobs:
  build_iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: |
            nixpkgs=channel:nixos-24.05
          extra_nix_config: |
            extra-platforms = riscv64-linux

      - uses: cachix/cachix-action@v15
        with:
          name: zlangjit-riscv64-01
          # per-cachix-account auth token
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: build iso --dry-run
        run: nix-build --dry-run -I "$(pwd)/nixpkgs" "<nixpkgs/nixos>" -A config.system.build.isoImage -I nixos-config=iso.nix

      - name: build iso
        run: nix-build -I "$(pwd)/nixpkgs" "<nixpkgs/nixos>" -A config.system.build.isoImage -I nixos-config=iso.nix

      - name: list files
        run: ls -lh result/iso

      - name: Release package
        uses: softprops/action-gh-release@master
        with:
          name: nixos
          tag_name:  nixos
          body: |
            nixos
          files: |
            result/iso/*
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
