name: Build NixOS Iso

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    # manual trigger
  #schedule:
  #  - cron: '0 0 * * *' # https://crontab.guru

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          sudo apt update
          sudo apt install -y qemu-user-static

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: |
            nixpkgs=channel:nixos-24.05
          extra_nix_config: |
            extra-platforms = riscv64-linux

      - uses: cachix/cachix-action@v15
        with:
          name: zlangjit-test-01
          # this is per-cachix-account auth token
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix-store -qR $(nix-instantiate default.nix)
      - run: nix-build --dry-run
      - run: nix-build

    #   - name: list files
    #     run: |
    #       ls -l

    #   - name: Release package
    #     uses: softprops/action-gh-release@master
    #     with:
    #       name: nixos
    #       tag_name:  nixos
    #       body: |
    #         nixos
    #       files: |
    #         out/*
    #       token: ${{ secrets.GITHUB_TOKEN }}
    #       fail_on_unmatched_files: true
