name: Termux GCC RiscV

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    # manual trigger
  #schedule:
  #  - cron: '0 0 * * *' # https://crontab.guru

defaults:
  run:
    shell: msys2 {0}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: '${{ matrix.icon }} Setup MSYS2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          path-type: strict
          
      - name: install git
        run: |
          pacman -Sy
          pacman -S --noconfirm --needed git

      - name: clone qemu_app
        run: |
          git clone https://github.com/mgood7123/qemu_app --depth=1

      - name: check if split program is cached
        run: |
          export MSYS=winsymlinks:native
          cd qemu_app
          chmod +x ./try_get_release.sh
          ./try_get_release.sh   mgood7123   qemu_app   storage--split--windows   split.exe.tar

      - name: unpack alpine
        run: |
          cd qemu_app
          ./unpack.sh
          cd alpine
          ls -l
          chmod -v +x *.sh
          mkdir ../vcxserv

      - name: install qemu
        run: |
          pacman -S --noconfirm --needed pactoys sshpass rsync
          pacboy -S --noconfirm --needed qemu:p qemu-common:p qemu-guest-agent:p qemu-image-util:p

      - name: poweron alpine
        run: |
          cd qemu_app/alpine
          . ./poweron_alpine.sh

      - name: qemu - install git
        run: |
          cd qemu_app/alpine
          ./exe.sh "sudo apk add git"

      - name: qemu - clone termux packages
        run: |
          cd qemu_app/alpine
          ./exe.sh "git clone https://github.com/termux/termux-packages --depth=1"

      - name: qemu - install docker
        run: |
          cd qemu_app/alpine
          ./exe.sh "sudo apk add docker"
          ./exe.sh "sudo addgroup ${USER} docker"
          ./exe.sh "sudo rc-update add docker default"
          ./exe.sh "sudo service docker start"
          ./exe.sh "sudo docker info"

      - name: qemu - docker - build gcc riscv
        run: |
          cd qemu_app/alpine
          ./exe.sh "cd termux-packages ; sudo ./scripts/run-docker.sh git clone https://github.com/ZLangJIT/termux-gcc-riscv packages/gcc-riscv"
          ./exe.sh "cd termux-packages ; sudo ./scripts/run-docker.sh ./build-package.sh -I gcc-riscv"

      - name: qemu - list files
        run: |
          cd qemu_app/alpine
          ./exe.sh "cd termux-packages ; ls -l"
          ./exe.sh "cd termux-packages ; ls -l out"

      - name: pull packages
        run: |
          cd qemu_app/alpine
          ./pull.sh termux-packages/out

      - name: powerff alpine
        run: |
          cd qemu_app/alpine
          ./poweroff_alpine.sh

      - name: Release package
        uses: softprops/action-gh-release@master
        with:
          name: gcc-riscv
          tag_name:  gcc-risc
          body: |
            gcc riscv
          files: |
            out/*
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
